"""add_user_invitations

Revision ID: b429a8fd778c
Revises: 21b0d0d20401
Create Date: 2025-11-01 10:20:25.291572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b429a8fd778c"
down_revision: Union[str, Sequence[str], None] = "21b0d0d20401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope_type",
            sa.Enum("self", "subtree", "custom_set", name="scope_type"),
            nullable=False,
        ),
        sa.Column(
            "twofa_delivery",
            sa.Enum("sms", "email", name="twofa_delivery_type"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_user_invitations_invited_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_units.id"],
            name=op.f("fk_user_invitations_org_unit_id_org_units"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_invitations_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_invitations")),
    )
    op.create_index(
        op.f("ix_user_invitations_email"), "user_invitations", ["email"], unique=False
    )
    op.create_index(
        "ix_user_invitations_email_tenant",
        "user_invitations",
        ["email", "tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_invitations_tenant_id"),
        "user_invitations",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_invitations_token"), "user_invitations", ["token"], unique=True
    )
    op.create_table(
        "user_invitation_units",
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("org_unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["user_invitations.id"],
            name=op.f("fk_user_invitation_units_invitation_id_user_invitations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_units.id"],
            name=op.f("fk_user_invitation_units_org_unit_id_org_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "invitation_id", "org_unit_id", name=op.f("pk_user_invitation_units")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_invitation_units")
    op.drop_index(op.f("ix_user_invitations_token"), table_name="user_invitations")
    op.drop_index(op.f("ix_user_invitations_tenant_id"), table_name="user_invitations")
    op.drop_index("ix_user_invitations_email_tenant", table_name="user_invitations")
    op.drop_index(op.f("ix_user_invitations_email"), table_name="user_invitations")
    op.drop_table("user_invitations")
    # ### end Alembic commands ###
